### ISSUE TITLE
ショートコードのブロック対応

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey-member-post#4]

**Comment by kmix-39** [comment]
ショートコードをブロックで出す形ので試したんですが、今の状態だと微妙かもですね。
理由としては、ブロックエディター時って必ずログインしてるんで「ログインしています」って必ず出るんですよ…（汗

ログインフォームを表示したいってなると、ちょっとPHPの中でブロックエディター内かどうかを処理する仕組みも必要かもしれません。うーん…

**Comment by inc2734** [comment]
https://github.com/inc2734/snow-monkey-member-post/issues/19
